language: node_js
node_js:
  - lts/*
script:
  - npx lerna bootstrap
  - npx lerna run compile
  - npx lerna run test
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc
deploy:
  provider: script
  script: npx lerna publish -y -c from-package
  on:
    tags: true
    repo: ngeor/html-fmt
env:
  global:
    secure: JHFdPRocFeQFCVkL1tz7HmnVOPErDmRbxLrKyxFg3QkH8Bh8pLrzPjOSWxCGUbNPTr5Q3IUX++4jnz+JMY9BziZTjUeLcekCdKDnZhJOjHE72nDc5C9QmrHkqOejuh9NBNR16dMY6NyTsdFLGHT68eEUHl0l8T0qIY2wgLLq+R8Cf1///iKctVg3YKBTmZTpS6lDRk/lFFl4x3a8ibf0Bihi8zkuyg4UbVm5JDvMqjpRxnVCVWKJobj8BA+Zy8nq4s4pe3XuH4zdvlip0NPigZV10UQ73zlCenX0mJDWo9ARZ1o4cVl0uOG0fz0m3laVdPQoxwIm+SHbBEmZgpBlcDh8n7QnYBCpZsMjuQJ89D/qKwYS4votOTzeLmwbpE3QWaUrbWFLW+coBpkQn7ojKX6OcVxrRrGeojy2yq6F20IVQ/s+M+7X/bd427PmqB2OGYsbtHds/7dMi+JBPtxyeA8oScAJeOjHi5eUU1Emts0uCF1OfusxIueX7h0Ls2AI4hw4RdHWE/fShaUbcSr/XF9zCAU6HRAKygrEiaDuJjBP/Md0Z9grihFba0R2iug9pml+d6wsIxo0pdX6FfEdTnsa7zgUAiwI+joSmefXfcwzgzJQIU2HYdQH7uLev12mV33fKtgXBcYsGLpU8WQ6sUcXJAfTY+MpAChV0WWt9lk=
