name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node_js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up nodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'packages/*/package-lock.json'
    - name: Install lerna
      run: npm i -g lerna
    - run: lerna bootstrap
    - run: lerna run compile
    - run: lerna run test
